### ISSUE TITLE
todo week2

### ISSUE THREAD

**Issue by maartenmarx** [jaspervdh96/Scriptie-Sprekers-TK#1]
* Doe dit na: <https://towardsdatascience.com/multi-class-text-classification-with-scikit-learn-12f1e60e0a9f> voor 1 kabinetsperiode of zo
* Confusion matrix
     * Als een spreker fout wordt geklassificeerd, kan je de fout verklaren?
         * is het ook een regereingspartij of ook een oppositiepartij?
         * linker/rechter blok

**Comment by jaspervdh96** [comment]
![afbeelding](https://user-images.githubusercontent.com/19666278/38467606-87c70f6e-3b3b-11e8-90e4-cb912968e8b0.png)

**Comment by jaspervdh96** [comment]
Heb alleen tot op heden geen statistische methoden gevonden om te beoordelen of er een significant verschil zit tussen regering en oppositie, maar daar zoek ik nog naar.
