### ISSUE TITLE
Laatste feedback

### ISSUE THREAD

**Issue by jaspervdh96** [jaspervdh96/Scriptie-Sprekers-TK#15]
@maartenmarx 
Allereerst natuurlijk beterschap en jammer van de reis!

Maar om inderdaad toch gebruik te maken van de situatie, zou ik nog feedback mogen op de resultaten en discussie van deelvraag 3 (sectie 4.3 en 5.3)?
Link: https://github.com/jaspervdh96/Scriptie-Sprekers-TK/blob/master/Scriptie_Sprekers_TK.pdf
Alvast bedankt

**Comment by maartenmarx** [comment]
Hi Jasper,

Dit blijft een lastige onderzoeksvraag om grip op te krijgen. Hieronder mijn observaties. Succes! 


* L421: Iets als " Op basis ... definieren we $V_{ij}$, het verwachte aantal documenten van partij $i$ die foutief als behorende bij partij $j$ geklassificeerd worden, als  (en dan je mooie formule)
    * dan geef je eerst in woorden aan wat Vij nou gaat betekenen? De verwachte fout.
* l421. Ik snap je formule eigenlijk nog steeds niet. 
    1. Ik stel voor dat je dit ook opneemt en laat zien dat het waar is met jouw defunitie: $\Sigma_{j\neq i}V_{ij}= fn_i$.
         * Leg echt de intuitie erachter uit. Want Loek gaat daar zeker naar vragen zoals het nu is. Dus je moet het toch ook echt kunnen!
    2. Ikzelf zou eerder dit verwachten als definitie $V_{ij}= fn_i\cdot P(j)$, where $P(j)$ is simply the number of j-documents divided by the total number of documents, or the ratio of j-documents.
    3. Dit model zou overeenkomen met het gooien van een pijltje (zonder te richten) op een plategroend van de 2e kamer waarin het aantal zetels gegegevn is door het aantal keer dat ze spraken (= het aantal docs).
* l422, 426 hier verwissel je toch weer i en j. Ik raak opnieuw in de war. ;-)
* equation (6) wat is $D_{ij}$? Is dat al eerder uitgelegd?
* _worden deze errors bij elkaar in distributie ge-
434 nomen._ wat betekent dit?

### Sectie 3.2.3.

* Ik zou zo beginnen (zo heb ik het althans begrpenen). "We gaan deze vraag op drie manieren beantwoorden. Twee daarvan kopieren we van Hirst et al. De derde is zelf ontwikkeld. We beginnen met die laatste." 

### Sectie 4.3

* Figuur 4. 
   * Laat zien hoe je aan N komt in de caption met een voorbeeld. (makkelijkst uit (a))
   * Laat in de caption zien wat een (x,y) betekent in deze plotjes.
   * Geef voor elk subplot plot de \mu en \sigma.  Daar gaat het toch om?
* 529-531 en tabel 9. Ik begrijp niet wat hier nu met wat vergeleken wordt en wat het resultaat eigenlijk is. 
   * Ik zou eigenlijk het liefst een schatting van de bias zien: dus iets als de kans dat een PvdA doc als VVD wordt gezien is .X in plaats van de "voorspelde" .Y en omgekeerd is het .... . Je ziet dus dat er een verhoogde kans is dat een foutief geklassificeerd regeringsdocument als behorende tot de andere regeringspartij geklassificeerd wordt.

### 5.3

* Leg in de eerste alinea uit wat hier gaat gebeuren en wat de resultaten zijn. 

* 621-622. Ik zou een conclusie achter deze 2 zinnen plakken. _Het lijkt dus alsof de twee regeringspartijen lastig uit elkaar te houden zijn voor de classifier._
* Dit is een heel goede inleiding tot deze deelvraag, en laat zien dat die tercht is.
     * Dus zeg ook zoiets als dit: "Of het feit dat een partij in de coalitie of in de oppositie zit invloed heeft op de klassificatie onderzoeken we in Deelvraag 3 met 3 experimenten. Eigenlijk blijkt uit geen van deze 3 expeimenten dat deze partij-status invloed heeft. "
